### ISSUE TITLE
Bug: Smart Menu font color in 2nd level differs from 1st level and might even be invisible

### ISSUE THREAD

**Issue by BerengarWLehr** [moodle-an-hochschulen/moodle-theme_boost_union#459]
As visible in the screenshots _color_ and _background-color_ are not in line with the 1st level colors. The text is invisible due to the rule 

```css
.navbar.navbar-dark.bg-dark .nav-link, .navbar.navbar-dark.bg-primary .nav-link {
    color: #fff;
}
```
background color is overriden by 

```css
.moremenu .nav-link:hover, .moremenu .nav-link:focus {
    border-color: transparent;
    background-color: #f8f9fa;
}
```

![moodle-dev uni-jena de_my_](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/65667914/bcdcbc1c-d09e-49be-b484-225243f80d5e)
![moodle-dev uni-jena de_my_ (2)](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/65667914/e209edf4-8d4a-4dc0-a2f5-879675ecbcf5)

It would be splendid if the 2nd level would behave as the 1st level (also using the same border-radius) but also as the following css rule:
```css
.moremenu .dropdownmoremenu > .dropdown-menu .dropdown-menu .dropdown-item:hover,
.moremenu .dropdownmoremenu > .dropdown-menu .dropdown-menu .dropdown-item:focus {
    color: #fff;
    background-color: #002350;
}
```

**Comment by BerengarWLehr** [comment]
My not-so-nice-fix is:
```css
/* Fix für Github Boost Union Issue #459 */
.navbar.navbar-dark.bg-dark .dropdown-item + ul > li > a,
.navbar.navbar-dark.bg-primary .dropdown-item + ul > li > a {
    color: inherit;
}
.navbar.navbar-dark.bg-dark .dropdown-item + ul > li > a:hover,
.navbar.navbar-dark.bg-dark .dropdown-item + ul > li > a:focus,
.navbar.navbar-dark.bg-primary .dropdown-item + ul > li > a:hover,
.navbar.navbar-dark.bg-primary .dropdown-item + ul > li > a:focus {
    color: #fff !important;
    background-color: #002350;
}
.dropdown-menu > .dropdown-submenu > ul {
    border-radius: 0 !important;
}
/* Ende Fix */
```
